### PR TITLE
added-new-flutter-course

### PR DESCRIPTION
**Pull request by viveeeeeek**
Added two new flutter courses.
Thank You

### CODE REVIEW

**Review by viveeeeeek — COMMENTED** [review]
conflicts fixed

**Review by viveeeeeek — COMMENTED** [review]
fixed another conflict

**Review by viveeeeeek — COMMENTED** [review]
conflict fixes

**Review by viveeeeeek — COMMENTED** [review]
fix

**Review by viveeeeeek — COMMENTED** [review]
fix

**Review by viveeeeeek — COMMENTED** [review]
conflicts fix

**Review by viveeeeeek — COMMENTED** [review]
conflicts fixes

**Comment by viveeeeeek** [comment]
@viralvaghela checkout added some new flutter courses. 
Sorry for this commit spam, as I am new to open source am still exploring <3

**Comment by viralvaghela** [comment]
now ?

**Comment by viveeeeeek** [comment]
> now ?

Yup done! Thanks <3

**Pull request merged**
