### PR TITLE
added-flutter-firebase-course

### PR DESCRIPTION
**Pull request by viveeeeeek**
Added Flutter & Firebase course to create Flutter app from scratch, using Firebase Firestore (a real-time database) and Firebase authentication.

### CODE REVIEW

**Comment by viralvaghela** [comment]
@sonawane-vivek there is conflict, please solve that.

**Comment by viveeeeeek** [comment]
> 
> 
> @sonawane-vivek there is conflict, please solve that.

data.json is perfect.

**Review by viveeeeeek — COMMENTED** [review]
Resolved conflicts

**Review by viveeeeeek — COMMENTED** [review]
Resolved conflicts in data.json

**Review by viveeeeeek — COMMENTED** [review]
everything is already good in data.json

**Review by viveeeeeek — COMMENTED** [review]
fixed data.json

**Comment by viveeeeeek** [comment]
@viralvaghela conflicts solved.

**Pull request merged**
